modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mixins]]
    config="mixins.adaptiveboss.json"

[[mods]]
    modId="adaptiveboss"
    version="${mod_version}"
    displayName="Adaptive Boss"
    logoFile="logo.png"
    authors="MrWizard94"
    description="""
        Bosses observe how you fight and adapt their tactics every few seconds.
        Works with Wither, Ender Dragon, and any modded boss automatically.
    """

[[dependencies.adaptiveboss]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.adaptiveboss]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
